### ISSUE TITLE
出现报错

### ISSUE THREAD

**Issue by ocetars** [BERADQ/koishi-plugin-genshinvoice-vits#10]
稳定用了很多天，今天突然出现未知错误导致无法合成语音，报错信息如下
![db2a18efc8d1a2b8c94a3e34045bc20b](https://github.com/BERADQ/koishi-plugin-genshinvoice-vits/assets/74854972/dfe08e2b-4eb8-4bc6-b26e-d78fae3a7bc8)

**Comment by idranme** [comment]
该接口暂时关闭，可更换至 fish-speech-online 插件。
