### ISSUE TITLE
发生未知错误 这是日志

### ISSUE THREAD

**Issue by David-Liv** [BERADQ/koishi-plugin-genshinvoice-vits#12]
![image](https://github.com/BERADQ/koishi-plugin-genshinvoice-vits/assets/139309528/99a31980-60de-4b36-9410-7c23fa0069ac)
![image](https://github.com/BERADQ/koishi-plugin-genshinvoice-vits/assets/139309528/5dd35fff-90ae-4bdf-8065-d00e9b2053bd)

**Comment by idranme** [comment]
Duplicate of #10
