### ISSUE TITLE
希望讲者、语速等可以发消息时传参

### ISSUE THREAD

**Issue by yi03** [BERADQ/koishi-plugin-genshinvoice-vits#7]
现在只能固定某一个角色的声音，希望能加一个列出角色列表的指令，并且讲者、语速等参数可以在发消息时传递。
比如
gsvits --role 派蒙 你好
类似这样。
谢谢大佬！

**Comment by BERADQ** [comment]
如果指令参数指定role，应该是 `gsvits --role 派蒙_ZH 你好` 吧

**Comment by ZokuTe** [comment]
> 现在只能固定某一个角色的声音，希望能加一个列出角色列表的指令，并且讲者、语速等参数可以在发消息时传递。 比如 gsvits --role 派蒙 你好 类似这样。 谢谢大佬！

如果指令参数指定role，应该是 `gsvits --role 派蒙_ZH 你好` 吧

**Comment by yi03** [comment]
> > 现在只能固定某一个角色的声音，希望能加一个列出角色列表的指令，并且讲者、语速等参数可以在发消息时传递。 比如 gsvits --role 派蒙 你好 类似这样。 谢谢大佬！
> 
> 如果指令参数指定role，应该是 `gsvits --role 派蒙_ZH 你好` 吧

是的是的，应该是派蒙_ZH。不过感觉这样要输入的有点长，感觉可以再加一个语言参数。
gsvits --role 派蒙 --language zh 你好
类似这样，不加language参数的话默认是中文。

**Comment by ZokuTe** [comment]
> > > 现在只能固定某一个角色的声音，希望能加一个列出角色列表的指令，并且讲者、语速等参数可以在发消息时传递。 比如 gsvits --role 派蒙 你好 类似这样。 谢谢大佬！
> > 
> > 
> > 如果指令参数指定role，应该是 `gsvits --role 派蒙_ZH 你好` 吧
> 
> 是的是的，应该是派蒙_ZH。不过感觉这样要输入的有点长，感觉可以再加一个语言参数。 gsvits --role 派蒙 --language zh 你好 类似这样，不加language参数的话默认是中文。

API本身讲者就是要求传入 `派蒙_ZH` 哦，language 则是另一个参数了。

**Comment by yi03** [comment]
> > > > 现在只能固定某一个角色的声音，希望能加一个列出角色列表的指令，并且讲者、语速等参数可以在发消息时传递。 比如 gsvits --role 派蒙 你好 类似这样。 谢谢大佬！
> > > 
> > > 
> > > 如果指令参数指定role，应该是 `gsvits --role 派蒙_ZH 你好` 吧
> > 
> > 
> > 是的是的，应该是派蒙_ZH。不过感觉这样要输入的有点长，感觉可以再加一个语言参数。 gsvits --role 派蒙 --language zh 你好 类似这样，不加language参数的话默认是中文。
> 
> API本身讲者就是要求传入 `派蒙_ZH` 哦，language 则是另一个参数了。

感觉可以把用户传入的language和role参数拼起来。比如如果传入的参数是派蒙+zh的话就拼成派蒙_ZH再传给服务器；如果是可莉+jp的话就拼成可莉_JP再传给服务器。类似这样。

**Comment by ZokuTe** [comment]
> > > > > 现在只能固定某一个角色的声音，希望能加一个列出角色列表的指令，并且讲者、语速等参数可以在发消息时传递。 比如 gsvits --role 派蒙 你好 类似这样。 谢谢大佬！
> > > > 
> > > > 
> > > > 如果指令参数指定role，应该是 `gsvits --role 派蒙_ZH 你好` 吧
> > > 
> > > 
> > > 是的是的，应该是派蒙_ZH。不过感觉这样要输入的有点长，感觉可以再加一个语言参数。 gsvits --role 派蒙 --language zh 你好 类似这样，不加language参数的话默认是中文。
> > 
> > 
> > API本身讲者就是要求传入 `派蒙_ZH` 哦，language 则是另一个参数了。
> 
> 感觉可以把用户传入的language和role参数拼起来。比如如果传入的参数是派蒙+zh的话就拼成派蒙_ZH再传给服务器；如果是可莉+jp的话就拼成可莉_JP再传给服务器。类似这样。

那么`mix`和`auto`呢

**Comment by yi03** [comment]
> > > > > > 现在只能固定某一个角色的声音，希望能加一个列出角色列表的指令，并且讲者、语速等参数可以在发消息时传递。 比如 gsvits --role 派蒙 你好 类似这样。 谢谢大佬！
> > > > > 
> > > > > 
> > > > > 如果指令参数指定role，应该是 `gsvits --role 派蒙_ZH 你好` 吧
> > > > 
> > > > 
> > > > 是的是的，应该是派蒙_ZH。不过感觉这样要输入的有点长，感觉可以再加一个语言参数。 gsvits --role 派蒙 --language zh 你好 类似这样，不加language参数的话默认是中文。
> > > 
> > > 
> > > API本身讲者就是要求传入 `派蒙_ZH` 哦，language 则是另一个参数了。
> > 
> > 
> > 感觉可以把用户传入的language和role参数拼起来。比如如果传入的参数是派蒙+zh的话就拼成派蒙_ZH再传给服务器；如果是可莉+jp的话就拼成可莉_JP再传给服务器。类似这样。
> 
> 那么`mix`和`auto`呢

我才发现还有mix和auto这两种。那要不ZH, JP, EN这三种用我说的那个拼起来的办法。如果language传入的是mix或auto的话就必须要输入全名？

**Comment by ZokuTe** [comment]
我想还是不要做这种脱离标准的事情，这个API的提供者不是我，而是另一位大佬，应该以他为标准。
所以我将会增加可选项：
- `speaker` _讲者_
  > example: `派蒙_ZH`
  > type: `string`


- `language` _语言_
  > example: `ZH`
  > type:`string`


- `length` _语速_
  > example: `1.0`
  > type:`float`


- `noise` _情感_
  > example: `0.6`
  > type:`float`


- `noisew` _音素长度_
  > example: `0.9`
  >type:`float`

**Comment by yi03** [comment]
> 我想还是不要做这种脱离标准的事情，这个API的提供者不是我，而是另一位大佬，应该以他为标准。
> 所以我将会增加可选项：
> - `speaker` _讲者_
>   > example: `派蒙_ZH`
>   > type: `string`
> 
> 
> - `language` _语言_
>   > example: `ZH`
>   > type:`string`
> 
> 
> - `length` _语速_
>   > example: `1.0`
>   > type:`float`
> 
> 
> - `noise` _情感_
>   > example: `0.6`
>   > type:`float`
> 
> 
> - `noisew` _音素长度_
>   > example: `0.9`
>   >type:`float`

好的好的，我现在也觉得还是直接用api提供者的标准比较好。因为我发现有几个speaker是没有语言后缀的，之后的后缀命名标准也可能会变。
谢谢大佬！
