### ISSUE TITLE
源域名似乎换了

### ISSUE THREAD

**Issue by March-7th-Tech** [BERADQ/koishi-plugin-genshinvoice-vits#9]
作者您好，genshinvoice.top 这个域名目前换成了 bv2.firefly.matce.cn 这个域名，导致整个插件挂了，如果有空的话麻烦作者update一下

**Comment by idranme** [comment]
1.2.0 updated

**Comment by March-7th-Tech** [comment]
> 1.2.0 updated

Love from China

**Comment by miaomiao2970** [comment]
又换回去了这是？
